# Generated by Django 4.2.2 on 2023-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_rating_comment_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating_author',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
